# Use an existing docker image as a base
FROM node:16-alpine

WORKDIR '/app'

# Download and install a dependency
COPY ./package.json ./
RUN npm install

RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

COPY ./ ./


# Tell the image what to do when it starts
CMD [ "npm", "run", "start" ]
